export const ROUTE_PATHS = {
  home: '/',
  dashboard: '/dashboard',
  servers: '/servers',
  serverDetail: '/servers/:serverId',
  tools: '/tools',
  toolDetail: '/tools/:toolId',
  toolExecute: '/tools/:toolId/execute',
  utilityTool: '/tools/utility/:toolSlug',
  mtoGenerator: '/mto-generator',
  executionConsole: '/execute',
  resources: '/resources',
  resourceDetail: '/resources/:resourceId',
  prompts: '/prompts',
  promptDetail: '/prompts/:promptId',
  executions: '/executions',
  executionDetail: '/executions/:executionId',
  logs: '/logs',
  integrations: '/integrations',
  settings: '/settings',
  settingsGeneral: '/settings/general',
  settingsSecurity: '/settings/security',
  settingsAppearance: '/settings/appearance',
  settingsConnection: '/settings/connection',
} as const

export const STORAGE_KEYS = {
  theme: 'mcpl-tools.theme',
  appSettings: 'mcpl-tools.settings',
  recentExecutions: 'mcpl-tools.recent-executions.v2',
  mtoRows: 'mcpl-tools.mto-rows.v1',
} as const
